version: '3.5'

services:

  mfurquim-grafana:
    build: .
    ports:
      - 3000:3000
    volumes:
      - grafana:/data

  mfurquim-prometheus:
    image: prometheus_prometheus:latest
    ports:
      - 9090:9090
    environment:
      - STATIC_SCRAPE_TARGETS=generator@generator:3000
    volumes:
      - prometheus:/prometheus
          
networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: 192.168.15.0/24

volumes:
  grafana:
  prometheus:

