{
 "title": "Obnoarding Prometheus",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "URIs",
    "query": "http_requests_duration_seconds_sum"
   }
  ]
 },
 "panels": [
  {
   "title": "Requests per Second and Average Time per Request",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Requests per Second and Average Time per Request for $URIs",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 1 },
   "repeat": "URIs",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_requests_duration_seconds_count{uri=\"$URIs\"}[1h])) by (uri) ",
     "legendFormat": "Requests per Second"
    },
    {
     "expr": "sum(http_requests_duration_seconds_sum{uri=\"$URIs\"}/http_requests_duration_seconds_count{uri=\"$URIs\"}) by (uri)",
     "legendFormat": "Average Time per Requests"
    }
   ]
  },
  {
   "title": "Top 10 URLs with a high average response time",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Top 10 URLs with high average response time",
     "type": "table",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
     "targets": [
      {
       "expr": "topk(10, http_requests_duration_seconds_sum{status =~ \"(2.*)\"}/http_requests_duration_seconds_count{status =~ \"(2.*)\"})"
      }
     ]
    },
    {
     "title": "Top 10 URLs with a high average response time over time",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk(10, http_requests_duration_seconds_sum{status =~ \"(2.*)\"}/http_requests_duration_seconds_count{status =~ \"(2.*)\"})"
      }
     ]
    }
   ]
  },
  {
   "title": "Top 10 URLs with more % errors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "Top 10 URLs with more % errors",
     "type": "table",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 2 },
     "targets": [
      {
       "expr": "sort_desc(topk(10, sum(http_requests_duration_seconds_count{status!~\"(2.*)\"}) by (uri)/sum(http_requests_duration_seconds_count) by (uri)))"
      }
     ]
    },
    {
     "title": "Top 10 URLs with more % errors over time",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk(10, sum(http_requests_duration_seconds_count{status!~\"(2.*)\"}) by (uri)/sum(http_requests_duration_seconds_count) by (uri))"
      }
     ]
    }
   ]
  }
 ]
}